# Generated by Django 4.2.16 on 2024-11-03 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0003_friend_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='following',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='slug',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friend_relation', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_relation', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
