# Generated by Django 4.2.16 on 2024-10-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='unread_messages',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
