# Generated by Django 4.2.16 on 2024-10-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_chatroom_unread_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='unread_messages',
            field=models.BooleanField(default=False),
        ),
    ]
